services:
  - type: web
    name: pasr
    env: node
    plan: standard
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install --legacy-peer-deps
    startCommand: cd backend && node app.js
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
